# Site settings
title: A. K. A. Jut
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  My personal web site to share information about myself and my interests.
baseurl: "/jekyll-ghpages" # the subpath of your site, e.g. /blog/
url: "http://akajut.github.io" # the base hostname & protocol for your site
twitter_username: akajut
github_username:  akajut

# Build settings
markdown: kramdown
